name: news_app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_webview_plugin: ^0.3.0+2
  # path_provider: ^0.4.1
  # url_launcher:
  share:
  intl:
  firebase_admob: ^0.5.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  # - assets\news_logo\dainik_janambhumi_logo.jpg
  # - assets\news_logo\pratidin_logo_2.png
  # - assets\news_logo\amar_axom.png
  # - assets\news_logo\assam_triune_app.gif
  # - assets\news_logo\dainik_purpodai.jpg
  # - assets\news_logo\gana_adhikar.png
  # - assets\news_logo\n_barta.jpg
  # - assets\news_logo\pratidin_logo_2.png
  # - assets\news_logo\sadin.png
  # - assets\news_logo\samayikprasanga.png
  # - assets\news_logo\sentinal_logo.png
  # - assets\news_logo\amar_axom.png
  - assets\news_logo\log_dainik_janambhumi.jpg
  - assets\news_logo\logo_pratidin.jpg
  - assets\news_logo\logo_n_barta.jpg
  - assets\news_logo\logo_amar_axom.jpg
  - assets\news_logo\logo_gana_adhikar.jpg
  - assets\news_logo\logo_hadin.jpg
  - assets\news_logo\logo_tribune.jpg
  - assets\news_logo\logo_purbanchal.jpg
  - assets\news_logo\logo_sentinal.jpg
  - assets\news_logo\logo_dainik_purpadai.jpg
  - assets\news_logo\logo_prasanga.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
